# Host and port of the application
HOST: localhost
PORT: 32000

# URL of the fink_cutout_api
CUTOUTAPIURL: http://localhost

# HBase configuration
HBASEIP: localhost
ZOOPORT: 2183

# Table schema (schema_{fink_broker}_{fink_science})
SCHEMAVER: schema_3.1_5.21.14

# Maximum number of rows to
# return in one call
NLIMIT: 10000
